handle spaces in directories
RockefellerArchiveCenter/iiif-image-scripts pull request #83
Opened 2021-04-06 14:52 UTC by p-galligan

Handles spaces in original file and derivative paths.

Updates readme.

Fixes #67

2021-04-06 15:34 UTC, helrond commented on iiif_pipeline/derivatives.py
> +                print(cmd)
Stray print

2021-04-06 15:35 UTC, helrond approved these changes
Can you add a test for this?

2021-04-06 15:35 UTC, helrond requested changes
Err I meant to request changes...

2021-04-06 18:12 UTC, helrond approved these changes

2021-04-06 18:24 UTC, helrond approved these changes

2021-04-07 13:40 UTC, bonniegee approved these changes

2021-04-07 13:48 UTC, merged